import React, { useState, useRef, useEffect } from 'react';
import { NaatResponse } from '../types';
import { Play, Square, Loader2, Share2, Copy, Music } from 'lucide-react';
import { generateNaatAudio } from '../services/geminiService';

interface NaatDisplayProps {
  data: NaatResponse;
}

const NaatDisplay: React.FC<NaatDisplayProps> = ({ data }) => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [isAudioLoading, setIsAudioLoading] = useState(false);
  const [audioBuffer, setAudioBuffer] = useState<AudioBuffer | null>(null);
  
  // Refs for audio context
  const audioContextRef = useRef<AudioContext | null>(null);
  const sourceNodeRef = useRef<AudioBufferSourceNode | null>(null);

  const handlePlayAudio = async () => {
    // If already playing, stop
    if (isPlaying) {
      if (sourceNodeRef.current) {
        sourceNodeRef.current.stop();
        sourceNodeRef.current = null;
      }
      setIsPlaying(false);
      return;
    }

    try {
      let bufferToPlay = audioBuffer;

      // If no buffer, fetch it
      if (!bufferToPlay) {
        setIsAudioLoading(true);
        // Combine title and lyrics for recitation
        const fullText = `${data.title}. ${data.urduLyrics.join(' ')}`;
        bufferToPlay = await generateNaatAudio(fullText);
        setAudioBuffer(bufferToPlay);
        setIsAudioLoading(false);
      }

      // Play buffer
      if (bufferToPlay) {
        if (!audioContextRef.current) {
          audioContextRef.current = new (window.AudioContext || (window as any).webkitAudioContext)({ sampleRate: 24000 });
        }
        
        // Ensure context is running (browser policy)
        if (audioContextRef.current.state === 'suspended') {
          await audioContextRef.current.resume();
        }

        const source = audioContextRef.current.createBufferSource();
        source.buffer = bufferToPlay;
        source.connect(audioContextRef.current.destination);
        source.onended = () => setIsPlaying(false);
        source.start();
        sourceNodeRef.current = source;
        setIsPlaying(true);
      }
    } catch (error) {
      console.error("Playback failed", error);
      setIsAudioLoading(false);
      setIsPlaying(false);
    }
  };

  const handleCopy = () => {
    const text = `${data.title}\n\n${data.urduLyrics.join('\n')}\n\nGenerated by Naat Nigar`;
    navigator.clipboard.writeText(text);
    alert('Naat copied to clipboard!');
  };

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (sourceNodeRef.current) {
        sourceNodeRef.current.stop();
      }
      if (audioContextRef.current) {
        audioContextRef.current.close();
      }
    };
  }, []);

  return (
    <div className="w-full max-w-4xl mx-auto mt-10 p-6 md:p-10 bg-white rounded-3xl shadow-xl border border-emerald-100 relative overflow-hidden">
      {/* Decorative Top Border */}
      <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-emerald-600 via-amber-400 to-emerald-600"></div>

      {/* Header Actions */}
      <div className="flex justify-between items-start mb-8">
        <div className="flex space-x-2">
           <button 
            onClick={handlePlayAudio}
            className={`flex items-center gap-2 px-4 py-2 rounded-full transition-all duration-300 ${
              isPlaying 
                ? 'bg-amber-100 text-amber-700 hover:bg-amber-200' 
                : 'bg-emerald-600 text-white hover:bg-emerald-700 shadow-lg hover:shadow-emerald-200'
            }`}
          >
            {isAudioLoading ? (
              <Loader2 className="w-5 h-5 animate-spin" />
            ) : isPlaying ? (
              <Square className="w-5 h-5 fill-current" />
            ) : (
              <Play className="w-5 h-5 fill-current" />
            )}
            <span className="font-semibold text-sm">
              {isAudioLoading ? 'Generating Audio...' : isPlaying ? 'Stop Recitation' : 'Listen'}
            </span>
          </button>
        </div>
        
        <div className="flex space-x-2">
          <button onClick={handleCopy} className="p-2 text-slate-400 hover:text-emerald-600 transition-colors" title="Copy Text">
            <Copy className="w-5 h-5" />
          </button>
          <button className="p-2 text-slate-400 hover:text-emerald-600 transition-colors" title="Share">
            <Share2 className="w-5 h-5" />
          </button>
        </div>
      </div>

      {/* Title */}
      <div className="text-center mb-10">
        <h2 className="font-heading-urdu text-4xl md:text-5xl text-emerald-900 mb-2 leading-tight">
          {data.title}
        </h2>
        <div className="w-24 h-1 bg-amber-400 mx-auto rounded-full mt-4"></div>
      </div>

      {/* Lyrics */}
      <div className="space-y-8 text-center" dir="rtl">
        {data.urduLyrics.map((verse, idx) => (
          <div key={idx} className="relative group">
            <p className="font-urdu text-2xl md:text-3xl text-slate-800 leading-loose hover:text-emerald-800 transition-colors cursor-default">
              {verse}
            </p>
            {/* Roman Transliteration (Hidden by default, visible on hover - optional design choice, here simply displayed below) */}
            <p className="text-sm text-slate-400 font-light mt-1 font-sans dir-ltr opacity-60">
              {data.transliteration[idx]}
            </p>
          </div>
        ))}
      </div>

      {/* English Summary */}
      <div className="mt-12 pt-8 border-t border-slate-100 text-center">
        <h3 className="text-xs font-bold tracking-widest text-emerald-600 uppercase mb-2">Summary</h3>
        <p className="text-slate-600 italic leading-relaxed max-w-2xl mx-auto">
          "{data.englishTranslation}"
        </p>
      </div>

      {/* Decorative Bottom Pattern */}
      <div className="absolute bottom-0 left-0 w-full h-32 bg-[url('https://www.transparenttextures.com/patterns/arabesque.png')] opacity-5 pointer-events-none"></div>
    </div>
  );
};

export default NaatDisplay;
